name: bt_game
description: Buttons game

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  redux: ^5.0.0
  flame: ^1.0.0
  json_annotation: ^4.1.0
  redux_epics: ^0.15.0
  built_value: ^8.1.1
  build_runner: ^2.1.2
  built_collection: ^5.1.0
  built_value_generator: ^8.0.4
  json_serializable: ^5.0.2
  logger: ^1.1.0
  meta: ^1.4.0
  get_it: ^7.2.0
  bt_logic:
    path: '../bt-logic'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Amatic
      fonts:
        - asset: fonts/AmaticSC-Regular.ttf
        - asset: fonts/AmaticSC-Bold.ttf
  assets:
    - assets/images/sprites.png

